### ISSUE TITLE
V15 lässt sich nicht installieren.

### ISSUE THREAD

**Issue by schoebelh** [ntimo/graylog-mailcow-content-pack#2]
Hallo,

im Gegensatz zu V14 lässt sich V15 zwar im Graylog uploaden, aber nicht installieren. Die Installation bricht mit einer Fehlermeldung im Graylog ab.

Ist es ok, dass V15 deutlich kleiner als V14 ist...? (131k <> 173k)

VG...

...Hagen

**Comment by heavygale** [comment]
Deinstalliere die V14 und lösche anschließend noch manuell die Pipeline Rules (/system/pipelines/rules), danach sollte es klappen.

**Comment by schoebelh** [comment]
Perfekt...! Danke für den Tip, so hat es funktioniert.
