### ISSUE TITLE
Dovecot Charts leer...

### ISSUE THREAD

**Issue by schoebelh** [ntimo/graylog-mailcow-content-pack#4]
Heute ist mir aufgefallen, dass die beiden Charts im Dashboard für Dovecot ("User countries" und "Top user") leer bleiben - das hat aber definitiv schon einmal funktioniert...

Alles Andere sieht gut aus.

Woran könnte das liegen?

VG...
...Hagen

**Comment by ntimo** [comment]
Habe gerade mal geschaut, bei mir sind die auch leer. Werde das heute Abend noch fixen und dann neu pushen :).

**Comment by ntimo** [comment]
Du kannst einfach unter System --> Grok Patterns und dann da nach `DOVECOT_TIME` suchen und das was da drin ist doch das hier Erstzen? `%{WORD}  %{NUMBER} %{TIME}`. Wichtig ist das zwischen %{WORD} und %{NUMBER} zwei Leerzeichen sind.

**Comment by schoebelh** [comment]
Ok - mit der Änderung wird "Dovecot: Top User" wieder befüllt. Danke!

Allerdings bleibt bei mir "Dovecot: User countries" weiterhin leer :-( ...

**Comment by schoebelh** [comment]
Merkwürdig - bei mir sind schon wieder beide Dovecot-Charts leer... Vorher hatte ich einen Fehler bei der GeoIP-Aktualisierung im Rahmen der Umstellung dort, da war auch das Postfix-Chart betroffen - DAS wird jetzt aber wieder befüllt.

Ist das nur bei mir so?

**Comment by heavygale** [comment]
Ich musste das zusätzliche Leerzeichen wieder entfernen,... scheinbar ist das nicht so richtig konsistent - am besten setzt du es so:

`%{WORD}%{SPACE}%{NUMBER} %{TIME}`

**Comment by schoebelh** [comment]
Ok - "Dovecot TopUser" wird mit der vorgeschlagenen Änderung wieder befüllt. "Dovecot User countries" bleibt bei mir aber weiter leer. :-(

**Comment by schoebelh** [comment]
Alles wieder da - Danke!
